version: "3.8"

services:

  mariadb:
    # image: mariadb
    container_name: mariadb
    build: ${CTR_PATH}/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env
    networks :
      - inception
    restart: always

  nginx:
    # image: nginx
    container_name: nginx
    build: ${CTR_PATH}/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always

  wordpress:
    # image: wordpress
    container_name: wordpress
    build: ${CTR_PATH}/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file :
      - .env
    networks:
      - inception
    restart: always


volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/sokaraku/data/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/sokaraku/data/wordpress
      o : bind
      type : none

networks:
  inception:
    name: inception