version: "3.8"

services:
  mariadb:
    container_name: mariadb
    build: ${CTR_PATH}/mariadb
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env
    networks :
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-zv", "mariadb", "3306"]
      interval: 1s
      timeout: 5s
      retries: 10
  nginx:
    container_name: nginx
    build: ${CTR_PATH}/nginx
    image: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
  wordpress:
    container_name: wordpress
    build: ${CTR_PATH}/wordpress
    image: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/wordpress
    env_file :
      - .env
    networks:
      - inception
    restart: always

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/sokaraku/data/mariadb
      o: bind
      type : none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/sokaraku/data/wordpress
      o: bind
      type : none

networks:
  inception:
    name: inception